[2025-02-08T10:09:09.225+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: pipeline_milestone_3.post_to_elasticsearch scheduled__2025-02-08T00:00:00+00:00 [queued]>
[2025-02-08T10:09:09.240+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: pipeline_milestone_3.post_to_elasticsearch scheduled__2025-02-08T00:00:00+00:00 [queued]>
[2025-02-08T10:09:09.240+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-02-08T10:09:09.240+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-02-08T10:09:09.240+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-02-08T10:09:09.249+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): post_to_elasticsearch> on 2025-02-08 00:00:00+00:00
[2025-02-08T10:09:09.259+0000] {standard_task_runner.py:52} INFO - Started process 1424 to run task
[2025-02-08T10:09:09.262+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'pipeline_milestone_3', 'post_to_elasticsearch', 'scheduled__2025-02-08T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_RizkySP_DAG.py', '--cfg-path', '/tmp/tmpmv3zvtyy', '--error-file', '/tmp/tmpvc_26dpm']
[2025-02-08T10:09:09.263+0000] {standard_task_runner.py:80} INFO - Job 19: Subtask post_to_elasticsearch
[2025-02-08T10:09:09.310+0000] {task_command.py:371} INFO - Running <TaskInstance: pipeline_milestone_3.post_to_elasticsearch scheduled__2025-02-08T00:00:00+00:00 [running]> on host b33620135048
[2025-02-08T10:09:09.347+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=RizkySP
AIRFLOW_CTX_DAG_ID=pipeline_milestone_3
AIRFLOW_CTX_TASK_ID=post_to_elasticsearch
AIRFLOW_CTX_EXECUTION_DATE=2025-02-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-02-08T00:00:00+00:00
[2025-02-08T10:09:09.486+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/P2M3_RizkySP_DAG.py", line 48, in post_to_elasticsearch
    es.index(index='retail_inventory', id=i, document=row.to_dict())
  File "/home/airflow/.local/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 168, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
TypeError: index() got an unexpected keyword argument 'document'
[2025-02-08T10:09:09.577+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=pipeline_milestone_3, task_id=post_to_elasticsearch, execution_date=20250208T000000, start_date=20250208T100909, end_date=20250208T100909
[2025-02-08T10:09:09.600+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 19 for task post_to_elasticsearch (index() got an unexpected keyword argument 'document'; 1424)
[2025-02-08T10:09:09.653+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-02-08T10:09:09.704+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
